### ISSUE TITLE
Failure to output JSON?

### ISSUE THREAD

**Issue by bclaymiles** [rfinnie/rdserialtool#2]
Hey there, I wanted to investigate the JSON output option, but rdserialtool bails when I run it with the json switch:
`root@Raspi PiB+ ntpviz: ~ # rdserialtool --json --bluetooth-address=xx:xx:xx:xx:xx:xx um25c         
rdserialtool 0.2
Copyright (C) 2019 Ryan Finnie

Connecting to UM25C xx:xx:xx:xx:xx:xx
Connection established

Traceback (most recent call last):
  File "/usr/local/bin/rdserialtool", line 11, in <module>
    load_entry_point('rdserialtool==0.2', 'console_scripts', 'rdserialtool')()
  File "/usr/local/lib/python3.5/dist-packages/rdserialtool-0.2-py3.5.egg/rdserial/tool.py", line 163, in main
  File "/usr/local/lib/python3.5/dist-packages/rdserialtool-0.2-py3.5.egg/rdserial/tool.py", line 156, in main
  File "/usr/local/lib/python3.5/dist-packages/rdserialtool-0.2-py3.5.egg/rdserial/um/tool.py", line 275, in main
  File "/usr/local/lib/python3.5/dist-packages/rdserialtool-0.2-py3.5.egg/rdserial/um/tool.py", line 250, in loop
  File "/usr/local/lib/python3.5/dist-packages/rdserialtool-0.2-py3.5.egg/rdserial/um/tool.py", line 121, in print_json
KeyError: 'data_groups'
root@Raspi PiB+ ntpviz: ~ # `

Not sure if I'm doing something wrong, or if it's an actual bug (no coding experience!)

**Comment by bclaymiles** [comment]
I should add that what I'm ultimately after is to isolate the Watt output to test against, for monitoring (with Monit).  I've tried writing the human output to a file to parse, but it's not ideal.

**Comment by rfinnie** [comment]
Thanks for noticing, this has now been fixed:

```
$ ./rdserialtool --json --bluetooth-address=00:15:A6:00:36:2F um25c | json_pp
rdserialtool 0.2.1
Copyright (C) 2019 Ryan Finnie

Connecting to UM25C 00:15:A6:00:36:2F
Connection established

{
   "volts" : 5.12,
   "record_seconds" : 0,
   "data_groups" : [
      {
         "amp_hours" : 0.008,
         "watt_hours" : 0.042
      },
      {
         "amp_hours" : 0,
         "watt_hours" : 0
      },
      {
         "amp_hours" : 0,
         "watt_hours" : 0
      },
      {
         "amp_hours" : 0,
         "watt_hours" : 0
      },
      {
         "watt_hours" : 0,
         "amp_hours" : 0
      },
      {
         "amp_hours" : 0,
         "watt_hours" : 0
      },
      {
         "watt_hours" : 0,
         "amp_hours" : 0
      },
      {
         "amp_hours" : 0,
         "watt_hours" : 0
      },
      {
         "amp_hours" : 0,
         "watt_hours" : 0
      },
      {
         "amp_hours" : 0,
         "watt_hours" : 0
      }
   ],
   "watts" : 0,
   "start" : 2505,
   "record_threshold" : 0.13,
   "collection_time" : 1556991482.3499,
   "data_line_negative_volts" : 0,
   "screen_timeout" : 2,
   "temp_c" : 24,
   "temp_f" : 76,
   "amps" : 0,
   "recording" : false,
   "data_group_selected" : 0,
   "screen_selected" : 1,
   "resistance" : 9999.9,
   "record_watthours" : 0,
   "record_amphours" : 0,
   "data_line_positive_volts" : 0.01,
   "screen_brightness" : 4,
   "end" : 65521,
   "charging_mode" : 7
}
```

**Comment by bclaymiles** [comment]
Awesome, thanks so much Ryan!!
