### ISSUE TITLE
Change refresh rate

### ISSUE THREAD

**Issue by raphaelcfernandes** [rfinnie/rdserialtool#3]
Hello, I'm using your code to connect the board to my linux machine and it works perfectly! However, I would like to read the data every 10ms, do you know if it's possible to change in some way the refresh rate of it? I'm using UM24C

**Comment by rfinnie** [comment]
--watch-seconds can take a portion of a second (--watch-seconds=0.01 for 10ms), but that's the time between polls, so it's 10ms + device poll time.  However, the device is way too slow to poll anywhere near 10ms, so the device is the limiting factor.
